name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  wait-for-img:
    name: "Wait for Image Build"
    runs-on: ubuntu-latest
    steps:
      - uses: autotelic/action-wait-for-status-check@v1
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: ${{ (github.event_name == 'pull_request') && 'pull-build' || 'main-build' }}
          timeoutSeconds: 180
          intervalSeconds: 10
      - name: Exit If Failing Build Requirement
        if: steps.wait-for-build.outputs.state != 'success'
        run: |
          echo "Image build did not succeed, skipping Smoke Test!"
          exit 1

  kustomize:
    strategy:
      matrix:
        flavor: ["", "-control-plane"]
    name: "Kustomize (dry-run${{ matrix.flavor }})"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: 'operator/go.mod'
          cache-dependency-path: 'operator/go.sum'
      - run: cd operator && make dry-run${{ matrix.flavor }} IMG='*:latest'
      - uses: actions/upload-artifact@v3
        with:
          retention-days: 5
          name: dry-run${{ matrix.flavor }}
          path: |
            operator/dry-run/*.yaml